<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Keywords and meta descriptions for the 195 Sustainable Solutions products.
 * Uses upsert (keyed on item_serial) so re-running is safe.
 */
class SustainableSolutionsMetaSeeder extends Seeder
{
    use WithoutModelEvents;

    public function run(): void
    {
        // [serial, keywords, meta_description]
        $meta = [
            [1152, 'rechargeable carabiner LED light eco folding torch sustainable promo', 'Compact rechargeable carabiner folding LED flashlight with eco-friendly branding for outdoor and corporate promotions.'],
            [1153, 'rechargeable zoom flashlight multi-mode LED eco sustainable promo tool', 'Versatile rechargeable multi-mode zoom flashlight — a sustainable branded gift for outdoors enthusiasts.'],
            [1154, 'SENSO 360 eco tumbler vacuum insulated leak proof promotional drinkware', 'Eco-friendly 16 oz SENSO 360 Explorer vacuum tumbler with leak-proof lid, ideal for sustainable brand campaigns.'],
            [1155, '360 Troy eco tumbler 16oz vacuum insulated recycled stainless steel', 'Branded 360 Troy 16 oz leak-proof vacuum tumbler crafted from recycled stainless steel for eco-conscious gifting.'],
            [1156, 'RPET sports bottle 30oz reusable recycled plastic eco promotional', 'Reeves 30 oz RPET reusable sports bottle made from recycled plastic — sustainable hydration branding solution.'],
            [1157, 'RPET sports bottle 22oz reusable recycled eco sustainable branded', 'Reeves 22 oz RPET sports bottle made from recycled plastic bottles for eco-minded promotional campaigns.'],
            [1158, 'RPET translucent bottle carabiner 25oz recycled plastic eco promo', 'Aloha 25 oz translucent RPET bottle with carabiner clip — a lightweight, recycled plastic hydration promo.'],
            [1159, 'recycled acrylic straw tumbler 20oz 2-in-1 eco branded clio', 'Clio 20 oz 2-in-1 recycled acrylic straw tumbler for sustainable brand gifting and on-the-go hydration.'],
            [1160, 'push pop spiral notebook house shape eco recycled paper promotional', 'Fun house-shaped push-pop spiral notebook with recycled paper pages — creative eco-branded writing gift.'],
            [1161, 'push pop spiral notebook round shape eco recycled paper branded', 'Round Push Pop spiral notebook with recycled paper — a playful, sustainable branded gift for any audience.'],
            [1162, 'RPET bottle carabiner 25oz recycled aloha eco sustainable branded water', 'Aloha 25 oz RPET reusable bottle with carabiner — recycled plastic hydration ideal for eco event giveaways.'],
            [1163, 'fargo 32oz recycled stainless steel bottle eco large capacity branded', 'Fargo 32 oz eco-friendly recycled stainless steel bottle — large-capacity sustainable drinkware with logo space.'],
            [1164, 'josi 25oz RPET sports bottle recycled plastic eco promotional hydration', 'Josi 25 oz RPET reusable sports bottle in recycled plastic — eco promotional drinkware for active audiences.'],
            [1165, 'lennon 20oz vacuum bottle straw lid eco recycled stainless sustainable', 'Lennon 20 oz eco-friendly vacuum bottle with straw lid — recycled stainless steel for sustainable giveaways.'],
            [1166, 'phantom 24oz tritan renew recycled bottle 2-in-1 eco branded sustainable', 'Phantom 24 oz 2-in-1 Tritan Renew recycled reusable bottle — transparent eco design for promotional branding.'],
            [1167, 'tasman 24oz RPET plastic bottle reusable recycled eco branded', 'Tasman 24 oz RPET reusable plastic bottle — affordable recycled drinkware for large eco-branded campaigns.'],
            [1168, 'triumph 3-in-1 charging cable USB hub recycled casing eco tech branded', 'Triumph 3-in-1 cable with 4-port USB hub in recycled casing — sustainable tech accessory for corporate gifting.'],
            [1169, 'lakeshore recycled nylon drawstring bag eco branded sustainable backpack', 'Lakeshore recycled nylon drawstring bag — lightweight, durable eco bag perfect for sustainable branded events.'],
            [1170, 'lakeshore recycled nylon tote bag eco sustainable branded shopping', 'Lakeshore recycled nylon tote — a durable, eco-friendly branded bag for shopping, trade shows, and events.'],
            [1171, 'lakeshore recycled nylon utility pouch carabiner eco branded organizer', 'Lakeshore recycled nylon utility pouch with carabiner — compact eco organizer for sustainable brand promotions.'],
            [1172, 'bamboo cutlery set cotton pouch eco sustainable kitchen branded utensils', 'Bamboo cutlery set in a cotton drawstring pouch — a zero-waste eco gift for sustainable kitchen promotions.'],
            [1173, 'alliance hardcover journal sticky flags pen eco recycled branded writing', 'Alliance hardcover eco journal with sticky flags and pen — professional sustainable branded writing set.'],
            [1174, 'artisan sketch pad colored pencil set 10-piece eco recycled branded art', 'Artisan sketch pad with 10-piece colored pencil set — sustainable branded art gift for creative professionals.'],
            [1175, 'avignon repreve recycled hardcover spiral notebook pen eco branded journal', 'Avignon Repreve recycled hardcover spiral notebook with pen — eco-certified branded writing companion.'],
            [1176, 'bamboo soft spiral notebook sticky notes eco sustainable branded writing', 'Bamboo soft spiral notebook with sticky notes — an eco-friendly branded writing gift combining bamboo and paper.'],
            [1177, 'canyon recycled softcover journal eco branded sustainable writing', 'Canyon recycled softcover journal — clean, minimalist eco branded writing notebook for every professional.'],
            [1178, 'camber spiral notebook sticky notes pen eco recycled branded', 'Camber spiral notebook with colorful sticky notes and pen — eco recycled paper branded writing bundle.'],
            [1179, 'centrum spiral notebook elastic closure eco recycled branded writing', 'Centrum eco spiral notebook with elastic closure — compact recycled branded notebook with secure closure.'],
            [1180, 'charter textured softcover journal pen eco recycled branded writing', 'Charter textured softcover journal with pen — eco recycled branded journal with premium textured cover.'],
            [1181, 'doodle mini softcover jotbook eco recycled compact branded notebook', 'Doodle mini softcover jotbook — pocket-sized eco recycled branded notebook for quick notes on the go.'],
            [1182, 'parley repreve recycled hardcover notebook eco branded sustainable writing', 'Parley Repreve recycled hardcover spiral notebook — ocean-plastic-inspired eco branded writing journal.'],
            [1183, 'heart push pop spiral notebook eco recycled branded fun writing gift', 'Heart-shaped Push Pop spiral notebook in recycled paper — a charming eco branded writing gift.'],
            [1184, 'paw push pop spiral notebook eco recycled branded animal pet promo', 'Paw Push Pop spiral notebook in recycled paper — fun eco branded notebook for animal and pet lovers.'],
            [1185, 'square push pop notebook eco recycled branded writing sustainable office', 'Square Push Pop spiral notebook — classic eco branded recycled paper notebook for office and events.'],
            [1186, 'praxis recycled spiral notebook sticky flags eco branded writing sustainable', 'Praxis recycled spiral notebook with sticky flags — organized eco branded writing gift for professionals.'],
            [1187, 'skywriter recycled ball pen highlighter eco branded combo office writing', 'Skywriter combo recycled plastic ball pen and highlighter — eco dual-function branded writing instrument.'],
            [1188, 'alaia 30oz 2-in-1 recycled stainless vacuum tumbler eco branded premium', 'Alaia 30 oz 2-in-1 recycled stainless steel vacuum tumbler — premium eco branded drinkware for top-tier gifts.'],
            [1189, 'luster 16oz recycled acrylic straw tumbler 2-in-1 eco branded sustainable', 'Luster 16 oz 2-in-1 recycled acrylic straw tumbler — stylish eco branded sustainable desk-to-gym companion.'],
            [1190, 'marli 20oz eco tumbler 2-in-1 recycled plastic branded sustainable drink', 'Marli 20 oz 2-in-1 eco-friendly tumbler in recycled plastic — compact sustainable branded drinkware choice.'],
            [1191, 'hex 6-in-1 light-up charging cable carabiner recycled eco tech sustainable', 'Hex 6-in-1 light-up charging cable with carabiner clip in recycled casing — eco tech gift with wow factor.'],
            [1192, 'quad USB hub 4-port USB-C USB-A recycled ABS eco branded tech', 'Quad 4-port USB-C and USB-A hub with recycled ABS case — eco branded desk tech for productivity.'],
            [1193, 'tetra 4-in-1 charging cable recycled phone stand eco tech branded', 'Tetra 4-in-1 charging cable with recycled case and built-in phone stand — eco-smart branded tech gift.'],
            [1194, 'cool clip rechargeable fan magnet base eco portable sustainable branded', 'Cool Clip rechargeable portable fan with magnet base — eco-friendly personal cooling for desk or outdoors.'],
            [1195, 'lexi 17oz eco vacuum bottle bamboo lid stainless branded sustainable', 'Lexi 17 oz eco vacuum stainless steel bottle with bamboo lid — nature-meets-performance sustainable drinkware.'],
            [1196, 'vida 22oz RPET sports bottle bamboo lid eco sustainable branded', 'Vida 22 oz RPET sports bottle with bamboo lid — recycled plastic and bamboo sustainable hydration combo.'],
            [1197, 'seneca 30oz eco straw mug recycled plastic sustainable branded drinkware', 'Seneca 30 oz eco-friendly straw mug in recycled plastic — large-capacity sustainable branded travel mug.'],
            [1198, 'talia 16oz eco vacuum insulated tumbler recycled stainless branded', 'Talia 16 oz eco vacuum insulated tumbler in recycled stainless steel — sleek branded sustainable drinkware.'],
            [1199, 'finger fidget spinner massage stress reliever eco branded promotional', 'Massage finger fidget spinner — an eco-friendly branded stress reliever for trade shows and wellness gifting.'],
            [1200, 'izzie 16oz eco vacuum tumbler recycled stainless branded sustainable', 'Izzie 16 oz eco vacuum insulated tumbler — compact recycled stainless steel branded drinkware for daily use.'],
            [1201, 'tuscany 24oz eco vacuum bottle 2-in-1 recycled stainless branded travel', 'Tuscany 24 oz eco 2-in-1 vacuum insulated bottle — versatile recycled stainless steel travel drinkware.'],
            [1202, 'eden 30oz eco recycled stainless bottle large capacity branded sustainable', 'Eden 30 oz eco-friendly recycled stainless steel bottle — generous branded drinkware for active lifestyles.'],
            [1203, 'havana 22oz recycled polypropylene tumbler silicone straw eco branded', 'Havana 22 oz recycled polypropylene tumbler with silicone straw — sustainable branded everyday tumbler.'],
            [1204, 'tonal 16oz eco tumbler recycled plastic branded sustainable drinkware', 'Tonal 16 oz eco friendly tumbler in recycled plastic — affordable sustainable branded everyday drinkware.'],
            [1205, 'alta 20oz eco vacuum straw mug recycled stainless branded sustainable', 'Alta 20 oz eco vacuum insulated straw mug in recycled stainless steel — sustainable branded commuter mug.'],
            [1206, 'minos 21oz eco 2-in-1 vacuum tumbler recycled stainless branded sustainable', 'Minos 21 oz eco 2-in-1 vacuum insulated tumbler — dual-mode recycled stainless branded drinkware.'],
            [1207, 'gateway RPET drawstring bag recycled eco branded lightweight backpack', 'Gateway RPET drawstring backpack — lightweight eco recycled branded bag for events and everyday use.'],
            [1208, 'bolt 4-in-1 bamboo RPET 100W charging cable eco sustainable branded tech', 'Bolt 4-in-1 bamboo and RPET 100W charging cable — high-power eco sustainable branded charging accessory.'],
            [1209, 'cask charging cable spinner portable eco branded recycled tech', 'Cask portable charging cable with fidget spinner — eco branded tech accessory perfect for trade show giveaways.'],
            [1210, 'americana RPET cooler lunch bag 2-compartment eco branded insulated', 'Americana 2-compartment RPET insulated lunch cooler bag — eco branded sustainable lunch carrier.'],
            [1211, 'crossroads 12-can RPET cooler bag eco branded insulated picnic', 'Crossroads 12-can RPET cooler bag — eco branded sustainable cooler for lunches, picnics, and outdoor events.'],
            [1212, 'custom athletic socks USA made eco recycled cotton branded apparel', 'Custom USA-made athletic socks in recycled cotton/polyester — eco-conscious branded apparel for active promotions.'],
            [1213, 'custom crew socks USA made recycled eco branded apparel promotional', 'Custom USA-made crew socks in eco recycled fabric — branded apparel staple for sustainable corporate gifting.'],
            [1214, 'custom ankle socks USA made eco recycled branded apparel sport', 'Custom USA-made ankle socks in recycled fabric — eco branded apparel for sport and wellness promotions.'],
            [1215, 'custom quarter crew socks USA made eco recycled athletic branded', 'Custom USA-made athletic quarter crew socks — eco sustainable branded apparel for active lifestyle gifting.'],
            [1216, 'bamboo phone stand keyboard stress reliever eco branded desk office', 'Bamboo phone stand with stress reliever keyboard — clever eco branded desk accessory for office gifting.'],
            [1217, 'rechargeable carabiner LED flashlight eco branded best buddy tools', 'Best Buddy Tools rechargeable carabiner LED flashlight — compact durable eco branded light for outdoors.'],
            [1218, 'canteen stackable lunch box utensils eco reusable branded kitchen', 'Canteen stackable lunch box with utensils — eco reusable branded kitchen set for sustainable meal prep.'],
            [1219, 'chuckwagon stackable lunch box bamboo lid eco branded sustainable kitchen', 'Chuckwagon stackable lunch box with bamboo lid and utensils — premium eco branded sustainable kitchen gift.'],
            [1220, 'harbor 40oz recycled tumbler straw large eco branded sustainable drinkware', 'Harbor 40 oz recycled tumbler with straw — giant eco branded sustainable drinkware for all-day hydration.'],
            [1221, 'fusion 5000mAh solar power bank eco charging sustainable branded tech', 'Fusion 5000 mAh solar-charging power bank — eco-powered branded tech gift for outdoor and sustainability events.'],
            [1222, 'corral hardcover journal eco recycled branded writing sustainable gift', 'Corral hardcover eco journal — clean, durable recycled branded writing book for professional gifting.'],
            [1223, 'evergreen kraft notebook eco recycled paper branded sustainable writing', 'Evergreen kraft notebook — natural kraft recycled paper branded notebook with an eco earthy feel.'],
            [1224, 'calypso insulated tote recycled polypropylene eco branded shopping bag', 'Calypso 75GSM recycled non-woven PP insulated tote — reusable eco branded bag for grocery and event use.'],
            [1225, 'ambassador executive spiral journal eco recycled branded premium writing', 'The Ambassador executive spiral journal — premium eco recycled branded journal for executive gifting.'],
            [1226, 'sanzio 21oz RPET bottle bamboo lid eco branded sustainable drinkware', 'Sanzio 21 oz RPET bottle with bamboo lid — recycled bottle meets natural bamboo in eco branded drinkware.'],
            [1227, 'avento 25oz recycled aluminum bottle silicone loop eco branded hydration', 'Avento 25 oz recycled aluminum bottle with silicone loop — lightweight eco branded hydration solution.'],
            [1228, 'husky 24oz RPET bottle recycled eco sustainable branded hydration', 'Husky 24 oz RPET bottle — rugged, recycled plastic eco branded water bottle for active lifestyles.'],
            [1229, 'switchback 27oz RPET snap-top carabiner bottle eco branded outdoor', 'Switchback 27 oz RPET snap-top bottle with carabiner — eco recycled branded hydration for outdoor adventures.'],
            [1230, 'rechargeable milk frother eco branded kitchen gadget bar coffee', 'Rechargeable milk frother — eco branded kitchen gadget for coffee lovers and sustainable lifestyle gifts.'],
            [1231, 'dynamo rechargeable portable vacuum cleaner eco branded home cleaning gift', 'Dynamo rechargeable portable vacuum cleaner — eco branded compact home cleaning gadget for practical gifting.'],
            [1232, 'cabrio 24oz recycled stainless vacuum bottle eco branded insulated', 'Cabrio 24 oz recycled stainless steel vacuum insulated bottle — premium eco branded sustainable drinkware.'],
            [1233, 'cabrio 32oz recycled stainless vacuum bottle eco branded large insulated', 'Cabrio 32 oz recycled stainless steel vacuum bottle — large-capacity eco branded sustainable drinkware.'],
            [1234, 'cameo 23oz PLA bioplastic sports bottle silicone loop eco branded hydration', 'Cameo 23 oz PLA bioplastic sports bottle with silicone loop — compostable-friendly eco branded drinkware.'],
            [1235, 'galley RPET insulated lunch bag eco branded sustainable food cooler', 'Galley RPET insulated lunch bag — recycled eco branded bag keeping meals fresh for daily commuters.'],
            [1236, 'reusable dryer balls cotton pouch eco sustainable branded home laundry', 'Toss N Dry 2-piece reusable dryer balls in natural rubber with cotton pouch — plastic-free eco branded laundry gift.'],
            [1237, 'on-the-go collapsible cutlery set wheat straw eco branded sustainable', 'On-The-Go collapsible cutlery set in wheat straw — zero-waste eco branded utensil set for conscious travelers.'],
            [1238, 'nosh recycled polypropylene lunch box eco branded sustainable container', 'Nosh recycled polypropylene lunch box — practical eco branded food container for everyday sustainable use.'],
            [1239, 'pitmaster recycled cotton apron eco branded kitchen grill sustainable chef', 'Pitmaster recycled cotton apron — eco branded kitchen/BBQ apron made from recycled cotton for chef-themed gifts.'],
            [1240, 'galaxy rechargeable LED lantern flashlight combo eco branded outdoor best buddy', 'Best Buddy Tools Galaxy rechargeable LED lantern and flashlight combo — eco branded outdoor lighting gift set.'],
            [1241, 'allure rechargeable dual pocket mirror LED eco branded beauty personal care', 'Allure rechargeable dual pocket mirrors with 2 light modes — eco branded personal care gift with rechargeable LED.'],
            [1242, 'duo beam rechargeable LED COB flashlight eco branded best buddy tools', 'Best Buddy Tools Duo Beam rechargeable LED and COB flashlight — dual-mode eco branded portable light.'],
            [1243, 'zoom rechargeable aluminum LED flashlight telescopic eco branded best buddy', 'Best Buddy Tools Zoom rechargeable aluminum telescopic-focus LED flashlight — professional eco branded torch.'],
            [1244, 'nexus 27oz recycled aluminum bottle flip-top carabiner eco branded', 'Nexus 27 oz recycled aluminum bottle with flip-top lid and carabiner — eco-light branded hydration for adventurers.'],
            [1245, 'magport bamboo 15W wireless charger eco branded FSC tech sustainable', 'Magport FSC bamboo 15W wireless charger — natural bamboo eco branded wireless charging pad for sustainable desks.'],
            [1246, 'aeroloft ECO crossbody mini backpack recycled polyester eco branded bag', 'AeroLOFT ECO anywhere crossbody mini backpack in recycled polyester — eco branded compact travel bag.'],
            [1247, 'aeroloft ECO belt bag recycled polyester eco branded sustainable travel', 'AeroLOFT ECO anywhere belt bag in recycled polyester — hands-free eco branded bag for events and travel.'],
            [1248, 'bamboo wireless speaker 10W wireless charger eco branded tech sustainable', 'FSC bamboo wireless speaker with 10W wireless charger — dual-function eco branded tech gift for green offices.'],
            [1249, 'FSC bamboo RPET mini power bank 2000mAh eco branded tech sustainable', 'FSC bamboo and RPET 2000 mAh mini power bank — pocket-sized eco branded tech gift for sustainable promotions.'],
            [1250, 'ecosound bamboo recycled aluminum wireless speaker eco branded audio', 'EcoSound bamboo and recycled aluminum wireless speaker — premium eco branded audio gift for sustainability events.'],
            [1251, 'traveler phone carrier lanyard adjustable eco branded bamboo sustainable', 'Traveler adjustable phone carrier and lanyard in bamboo and nylon — eco branded mobile accessory for events.'],
            [1252, 'mahogany wireless speaker wireless charger eco branded wood premium tech', 'Mahogany wireless speaker with wireless charger — warm natural wood eco branded tech gift for premium gifting.'],
            [1253, 'bamboo retractable 3-in-1 charging cable eco branded sustainable tech', 'Bamboo retractable 3-in-1 charging cable with dual inputs — compact eco branded bamboo charging solution.'],
            [1254, 'executive FSC journal grommet spine eco branded premium writing sustainable', 'Executive FSC journal with textured grommet spine — premium eco certified branded writing book for executives.'],
            [1255, 'grassfield cork recycled journal pen eco branded sustainable writing', 'GrassField cork recycled journal with pen — natural cork and recycled paper eco branded writing combo.'],
            [1256, 'bamboo dual USB type-C hub eco branded tech sustainable desk FSC', 'FSC bamboo dual-port USB and Type-C hub — natural eco branded desk tech for a sustainable workspace.'],
            [1257, 'plantation fruit nut pulp paper journal eco branded natural sustainable', 'Plantation fruit and nut pulp paper journal — unique natural eco branded journal with upcycled paper pages.'],
            [1258, 'lagoon 20oz RPET bottle recycled eco branded hydration sustainable', 'Lagoon 20 oz RPET bottle — compact recycled plastic eco branded water bottle for everyday hydration.'],
            [1259, 'bamboo multi-tool carabiner eco branded best buddy tools sustainable kit', 'Best Buddy Tools bamboo multi-tool with carabiner — eco branded bamboo tool kit for outdoor enthusiasts.'],
            [1260, 'bamboo coaster bottle opener eco branded FSC sustainable home bar', 'FSC bamboo coaster with bottle opener — dual-function eco branded bamboo home and bar gift item.'],
            [1261, 'savvy recycled journal eco branded sustainable writing affordable', 'Savvy recycled journal — affordable eco branded writing book made from recycled materials.'],
            [1262, 'elan hardcover journal pen loop inner pocket eco recycled branded writing', 'Elan hardcover journal with pen loop and inner pocket — organized eco recycled branded journal for professionals.'],
            [1263, 'elite softcover FSC leatherette journal eco branded premium sustainable', 'Elite softcover FSC leatherette journal — premium eco branded writing book with FSC certified cover.'],
            [1264, 'stirling 18oz glass tumbler silicone sleeve straw eco branded sustainable', 'Stirling 18 oz recycled glass tumbler with silicone sleeve and PP straw — premium eco branded drinkware.'],
            [1265, 'kraft recycled journal eco branded natural paper sustainable writing', 'Kraft recycled journal — natural, uncoated kraft paper eco branded journal for eco-conscious recipients.'],
            [1266, 'prairie fragrant grass recycled notebook pen eco branded sustainable', 'Prairie fragrant grass recycled spiral notebook with pen — unique scented eco paper branded writing diary.'],
            [1267, 'pop top bamboo bottle opener eco branded FSC sustainable bar gift', 'Pop Top FSC bamboo bottle opener — natural eco branded bar accessory for branded hospitality gifting.'],
            [1268, 'NAYAD cortado 16oz coffee grounds mug eco recycled branded drinkware', 'NAYAD Cortado 16 oz mug made from coffee grounds and recycled PP — upcycled eco branded drinkware gift.'],
            [1269, 'savanna jute recycled cotton backpack eco branded sustainable bag', 'Savanna jute and recycled cotton backpack — natural fiber eco branded backpack for sustainable gifting campaigns.'],
            [1270, 'savanna jute recycled cotton cooler bag eco branded sustainable insulated', 'Savanna jute and recycled cotton cooler bag — natural eco branded insulated bag for picnics and outdoor events.'],
            [1271, 'savanna jute recycled cotton drawstring backpack eco branded sustainable', 'Savanna jute and recycled cotton drawstring backpack — natural fiber eco branded bag for events and schools.'],
            [1272, 'savanna jute recycled cotton cooler tote eco branded sustainable bag', 'Savanna jute and recycled cotton cooler tote — durable eco branded natural bag for shopping and events.'],
            [1273, 'comet 2-in-1 COB lightbar LED headlamp rechargeable eco branded best buddy', 'Best Buddy Tools Comet 2-in-1 rechargeable COB lightbar and LED headlamp — eco branded versatile work light.'],
            [1274, 'retro pop up COB lantern rechargeable eco branded best buddy vintage light', 'Best Buddy Tools Retro Pop Up rechargeable COB lantern — classic eco branded lantern for outdoor branded events.'],
            [1275, 'agenda recycled notebook sticky notes pen eco branded sustainable office', 'Agenda recycled spiral notebook with sticky notes and pen — eco branded office writing set for organized gifting.'],
            [1276, 'flip recycled spiral notebook pen eco branded sustainable writing', 'Flip recycled spiral notebook with pen — simple eco branded writing bundle for everyday sustainable use.'],
            [1277, 'sovereign 4000mAh wireless power bank recycled eco branded tech sustainable', 'Sovereign 4000 mAh wireless charging power bank with recycled case — eco branded portable power for tech gifting.'],
            [1278, 'bamboo magnetic power clip eco branded FSC sustainable tech desk', 'FSC bamboo magnetic power clip — natural eco branded desk accessory combining sustainability and utility.'],
            [1279, 'bamboo portable phone stand eco branded FSC sustainable desk tech', 'Bamboo portable phone stand — slim eco branded FSC bamboo desk accessory for branded workspace essentials.'],
            [1280, 'bamboo bloc phone stand eco branded FSC sustainable desk office', 'Bamboo Bloc phone stand — compact eco branded bamboo phone holder for sustainable office and desk gifting.'],
            [1281, 'panda bamboo 15W wireless charger dual USB eco branded FSC sustainable', 'Panda FSC bamboo 15W wireless charger with dual USB ports — eco branded charging pad for green workspaces.'],
            [1282, 'bamboo mug warmer ceramic mug eco branded FSC sustainable office home', 'Bamboo mug warmer with 8 oz ceramic mug — eco branded bamboo and ceramic gift set for home and office.'],
            [1283, 'FSC bamboo wireless charger phone stand eco branded sustainable tech', 'FSC bamboo wireless charger and portable phone stand — eco branded 2-in-1 tech gift for sustainable offices.'],
            [1284, 'trident 15W wireless charger FSC cork recycled plastic eco branded', 'Trident 15W wireless charger in FSC cork and recycled plastic — eco certified branded charging pad.'],
            [1285, 'ovation 10W stereo speaker FSC cork recycled plastic eco branded audio', 'Ovation 10W stereo speaker in FSC cork and recycled plastic — eco certified branded audio gift.'],
            [1286, 'jot n plot FSC eco organizer notebook branded sustainable office writing', 'Jot N Plot FSC eco-friendly organizer notebook — certified eco branded writing and planning tool for offices.'],
            [1287, 'bamboo 5000mAh type-C power bank eco branded FSC sustainable charging', 'FSC bamboo 5000 mAh Type-C power bank — natural eco branded portable charger for sustainable brand gifting.'],
            [1288, 'FSC bamboo 5000mAh dual port power bank wireless charger eco branded', 'FSC bamboo 5000 mAh dual port power bank with wireless charging — premium eco branded tech combo gift.'],
            [1289, 'bamboo 3-in-1 39in charging cable eco branded FSC sustainable tech', 'Bamboo 3-in-1 39-inch charging cable — full-length eco FSC bamboo branded charging cable for any device.'],
            [1290, 'bamboo 3-in-1 6in charging cable compact eco branded FSC sustainable', 'Bamboo 3-in-1 6-inch charging cable — pocket-size eco FSC bamboo branded cable for travel and events.'],
            [1291, 'bamboo 10000mAh dual port power bank wireless charger eco branded FSC', 'Bamboo 10000 mAh dual port power bank with 10W wireless charging — large-capacity eco branded power solution.'],
            [1292, 'assay tape measure light 3ft eco branded recycled plastic sustainable tools', 'Assay 3 ft tape measure with LED light — compact eco branded recycled plastic measuring tool for branded kits.'],
            [1293, 'bamboo cutting board eco branded FSC sustainable kitchen gift', 'FSC bamboo cutting board — kitchen essential eco branded gift made from sustainable bamboo.'],
            [1294, 'carina RPET cork insulated cooler bag eco branded sustainable picnic', 'Carina RPET and cork insulated cooler bag — eco branded cooler combining recycled polyester and natural cork.'],
            [1295, 'carina RPET cork drawstring backpack eco branded sustainable bag', 'Carina RPET and cork drawstring backpack — eco branded recycled and natural material everyday backpack.'],
            [1296, 'carina RPET cork tote bag eco branded sustainable shopping bag', 'Carina RPET and cork tote bag — stylish eco branded recycled and cork material shopping and carry tote.'],
            [1297, 'pinnacle RPET polar fleece blanket dye sublimated eco branded sustainable', 'Pinnacle dye sublimated RPET polar fleece blanket — full-color eco branded recycled fleece ideal for corporate gifting.'],
            [1298, 'pinnacle RPET polar fleece blanket eco branded sustainable branded throw', 'Pinnacle RPET polar fleece blanket — cozy eco branded recycled polar fleece blanket for events and branded gifts.'],
            [1299, 'double decker lunch box FSC bamboo lid eco branded sustainable kitchen', 'Double decker lunch box with FSC bamboo lid and utensils — practical eco branded sustainable meal prep gift.'],
            [1300, 'bamboo sticky note dispenser phone holder eco branded FSC desk office', 'Bamboo sticky note dispenser with phone holder — versatile eco branded bamboo desk organizer gift.'],
            [1301, 'asbury 24oz recycled aluminum bottle eco branded sustainable hydration', 'Asbury 24 oz recycled aluminum bottle — lightweight eco branded drinkware for active and outdoor giveaways.'],
            [1302, 'northstar COB light magnet stand rechargeable eco branded best buddy tools', 'Best Buddy Tools Northstar rechargeable COB work light with magnet and stand — eco branded workshop essential.'],
            [1303, 'legion charging station ambient lamp 3-in-1 eco branded tech sustainable', 'Legion 3-in-1 charging station with ambient lamp — eco branded bamboo tech gift for modern sustainable offices.'],
            [1304, 'vaquero recycled leather journal eco branded sustainable writing notebook', 'Vaquero recycled leatherette journal — premium eco branded journal with recycled leather-look cover.'],
            [1305, 'schooner RPET canvas lunch tote eco branded sustainable bag insulated', 'Schooner RPET canvas lunch tote — lightweight eco branded recycled canvas bag for daily lunches.'],
            [1306, 'sloop RPET canvas drawstring backpack eco branded sustainable bag', 'Sloop RPET canvas drawstring backpack — durable eco branded recycled canvas backpack for daily and event use.'],
            [1307, 'bamboo 4-piece coaster set eco branded FSC sustainable home bar', 'Bamboo 4-piece coaster set — classic eco branded FSC bamboo coasters for home and corporate gifting.'],
            [1308, 'puebla 26oz RPET bottle recycled eco branded hydration sustainable', 'Puebla 26 oz RPET bottle — recycled plastic eco branded water bottle for everyday and event hydration.'],
            [1309, 'carnival RPET cooler tote eco branded sustainable insulated bag', 'Carnival RPET insulated cooler tote — eco branded recycled polyester cooler bag for events and outdoor use.'],
            [1310, 'orion recycled cotton drawstring backpack eco branded 5oz 50/50 sustainable', 'Orion 5 oz 50/50 recycled cotton drawstring backpack — lightweight eco branded natural bag for promotions.'],
            [1311, 'orion recycled cotton tote 10oz 50/50 eco branded sustainable shopping', 'Orion 10 oz 50/50 recycled cotton tote — classic eco branded natural fiber tote for shopping and events.'],
            [1312, 'bamboo marble combo coaster eco branded sustainable home bar gift', 'Bamboo and marble combo coaster — unique eco branded natural materials coaster for premium home gifting.'],
            [1313, 'lyra rechargeable COB worklight LED flashlight eco branded best buddy', 'Lyra rechargeable COB work light and LED flashlight combo — versatile eco branded portable lighting solution.'],
            [1314, 'starlight rechargeable LED headlamp eco branded best buddy sustainable outdoor', 'Best Buddy Tools Starlight rechargeable LED headlamp — hands-free eco branded headlamp for outdoor activities.'],
            [1315, 'farview roll up RPET knit beanie eco branded sustainable apparel winter', 'Farview roll up cuff RPET knit beanie — eco branded recycled beanie for winter and outdoor branded events.'],
            [1316, 'sundance RPET knit beanie eco branded sustainable apparel winter branded', 'Sundance RPET knit beanie — soft eco branded recycled knit beanie for cold weather promotional gifting.'],
            [1317, 'bamboo recycled polycarbonate UV400 sunglasses eco branded sustainable eyewear', 'Bamboo and recycled polycarbonate UV400 sunglasses — eco branded eyewear for outdoor events and summer promos.'],
            [1318, 'westgate recycled polycarbonate UV400 sunglasses eco branded sustainable', 'Westgate recycled polycarbonate UV400 sunglasses — eco branded lightweight eyewear for summer promotions.'],
            [1319, 'NAYAD neo 16oz coffee grounds recycled tumbler eco branded sustainable mug', 'NAYAD Neo 16 oz coffee grounds and recycled PP tumbler — upcycled eco branded mug for coffee culture gifting.'],
            [1320, 'broadway clip-on ring light eco branded rechargeable selfie video branded', 'Broadway clip-on ring light — eco branded rechargeable ring light for content creators and video calls.'],
            [1321, 'bike light gift set eco branded rechargeable cycling sustainable outdoor', 'Bike light gift set — eco branded rechargeable cycling lights for outdoor commuters and cycling enthusiasts.'],
            [1322, 'empire bamboo wireless speaker 5W wireless charger eco branded sustainable', 'Empire FSC bamboo wireless speaker with 5W wireless charger — dual-function eco branded audio tech gift.'],
            [1323, 'beam rechargeable pocket COB light clip magnet eco branded best buddy tools', 'Best Buddy Tools Beam rechargeable pocket COB light with clip and magnet — compact eco branded work light.'],
            [1324, 'cusano 22oz vacuum stainless bottle bamboo cap eco branded sustainable', 'Cusano 22 oz vacuum insulated stainless steel bottle with bamboo cap — eco branded premium steel and bamboo drinkware.'],
            [1325, 'milan 10oz ceramic tumbler bamboo lid eco branded sustainable coffee', 'Milan 10 oz ceramic tumbler with bamboo lid — artisan eco branded ceramic and bamboo drinkware gift.'],
            [1326, 'sunray RPET reusable shopping bag eco branded sustainable lightweight foldable', 'Sunray RPET reusable shopping bag — lightweight eco branded recycled polyester tote for zero-waste shopping.'],
            [1327, 'lucent rechargeable bike taillight eco branded cycling sustainable outdoor', 'Lucent rechargeable bike taillight — bright eco branded cycling safety light for outdoor enthusiasts.'],
            [1328, 'nightline COB LED headlamp rechargeable eco branded best buddy sustainable', 'Best Buddy Tools Nightline rechargeable COB and LED headlamp — dual-function eco branded headlamp for all uses.'],
            [1329, 'bazaar RPET folding tote eco branded sustainable reusable shopping bag', 'Bazaar RPET folding reusable tote bag — compact eco branded bag that folds flat for sustainable on-the-go use.'],
            [1330, 'grab n go RPET drawstring backpack eco branded budget sustainable promo', 'Grab N Go RPET budget drawstring backpack — affordable eco branded recycled bag for large promotional campaigns.'],
            [1331, 'wheatstraw tableware set 6-in-1 portable eco branded sustainable utensils', '6-in-1 portable wheat straw tableware set — plant-based eco branded cutlery set for zero-waste gifting.'],
            [1332, 'reprise RPET journal stone paper eco branded sustainable textured writing', 'Reprise RPET textured journal with amazing stone paper — innovative eco branded waterproof writing journal.'],
            [1333, 'revue RPET textured journal eco branded sustainable writing recycled', 'Revue RPET textured journal — stylish eco branded recycled journal with textured cover for professional gifting.'],
            [1334, 'allegro TWS earbuds solar charging case eco branded sustainable audio', 'Allegro TWS earbuds with solar-powered charging case — eco branded wireless audio gift with solar tech.'],
            [1335, 'sunrise alarm clock himalayan salt lamp wireless charger eco branded wellness', 'Sunrise alarm clock with Himalayan salt lamp and wireless charger — eco wellness branded gift for home offices.'],
            [1336, 'cafe sustainable to-go cup 17oz USA made eco branded recycled paperboard', 'Café 17 oz sustainable to-go cup USA made — eco branded recycled paperboard cup for green-conscious gifting.'],
            [1337, 'sip n stir bamboo mug spoon 12oz eco branded sustainable drinkware coffee', 'Sip N Stir 12 oz bamboo and polypropylene mug with spoon — eco branded bamboo drinkware for coffee lovers.'],
            [1338, 'chiller RPET cooling towel eco branded sustainable sport gym outdoor', 'Chiller RPET cooling towel — eco branded recycled polyester cooling towel for sports and outdoor events.'],
            [1339, 'eco wheat straw kit cleaning brush eco branded sustainable home utensils', 'Eco wheat straw kit with cleaning brush — plant-based eco branded reusable kit for zero-waste home use.'],
            [1340, 'doral wheat straw sunglasses eco branded sustainable eyewear plant-based', 'Doral wheat straw sunglasses — eco branded plant-based eyewear made from agricultural wheat straw.'],
            [1341, 'light-up tritan bottle solar lantern eco branded 20oz sustainable outdoor', 'Light-Up 20 oz Tritan bottle and solar lantern — eco branded dual-function drinkware and lighting gift set.'],
            [1342, 'promo write recycled notebook eco branded sustainable paper writing', 'Promo Write recycled notebook — classic eco branded recycled paper notebook for large-scale promo campaigns.'],
            [1343, 'recycle write notebook pen eco branded sustainable paper writing set', 'Recycle Write notebook and pen — eco branded recycled paper writing set for sustainable promotional gifting.'],
            [1344, 'think green recycled notepad pen eco branded sustainable office writing', 'Think Green recycled notepad and pen — eco branded message and writing set for environmental awareness campaigns.'],
            [1345, 'picnic RPET cooler bag eco branded sustainable insulated picnic outdoor', 'Picnic RPET cooler bag — eco branded recycled polyester insulated cooler bag for picnics and outdoor events.'],
            [1346, 'XL insulated RPET shopping bag eco branded large sustainable grocery tote', 'XL insulated RPET shopping bag — oversized eco branded recycled polyester insulated grocery and carry bag.'],
        ];

        $rows = array_map(fn ($m) => [
            'item_serial'      => $m[0],
            'keywords'         => $m[1],
            'meta_description' => $m[2],
        ], $meta);

        DB::table('product_meta')->upsert(
            $rows,
            ['item_serial'],
            ['keywords', 'meta_description']
        );
    }
}
